-- Secuencias para las claves primarias
CREATE SEQUENCE seq_bovedas START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_clientes START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_cuentas START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_departamentos START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_empleados START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_estados_prestamos START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_estado_financiero START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_est_tarjetas START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_historial_auditoria START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_historial_prestamos START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_historial_saldos START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_municipios START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_prestamos START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_roles START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_seguridad_acceso START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_sucs_agens START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_tarjs_cred START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_tipocuentas START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_tipo_sucs_agens START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_tipo_transacs START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_transacciones START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_transacciones_interbancarias START WITH 1 INCREMENT BY 1;


-- Trigger para clientes
CREATE OR REPLACE TRIGGER trg_clientes_id
BEFORE INSERT ON CLIENTES
FOR EACH ROW
WHEN (NEW.ID_CLIENTE IS NULL)
BEGIN
    :NEW.ID_CLIENTE := seq_clientes.NEXTVAL;
END;
/

-- Trigger para cuentas
CREATE OR REPLACE TRIGGER trg_cuentas_id
BEFORE INSERT ON CUENTAS
FOR EACH ROW
WHEN (NEW.ID_CUENTA IS NULL)
BEGIN
    :NEW.ID_CUENTA := seq_cuentas.NEXTVAL;
END;
/

-- Trigger para departamentos
CREATE OR REPLACE TRIGGER trg_departamentos_id
BEFORE INSERT ON DEPARTAMENTOS
FOR EACH ROW
WHEN (NEW.ID_DEPARTAMENTO IS NULL)
BEGIN
    :NEW.ID_DEPARTAMENTO := seq_departamentos.NEXTVAL;
END;
/

-- Trigger para empleados
CREATE OR REPLACE TRIGGER trg_empleados_id
BEFORE INSERT ON EMPLEADOS
FOR EACH ROW
WHEN (NEW.ID_EMPLEADO IS NULL)
BEGIN
    :NEW.ID_EMPLEADO := seq_empleados.NEXTVAL;
END;
/

-- Trigger para estados_prestamos
CREATE OR REPLACE TRIGGER trg_estados_prestamos_id
BEFORE INSERT ON ESTPRESTS
FOR EACH ROW
WHEN (NEW.ID_EPRESTAMO IS NULL)
BEGIN
    :NEW.ID_EPRESTAMO := seq_estados_prestamos.NEXTVAL;
END;
/

-- Trigger para estado_financiero
CREATE OR REPLACE TRIGGER trg_estado_financiero_id
BEFORE INSERT ON ESTFINACIEROS
FOR EACH ROW
WHEN (NEW.ID_ESTADO IS NULL)
BEGIN
    :NEW.ID_ESTADO := seq_estado_financiero.NEXTVAL;
END;
/

-- Trigger para est_tarjetas
CREATE OR REPLACE TRIGGER trg_est_tarjetas_id
BEFORE INSERT ON EST_TARJETAS
FOR EACH ROW
WHEN (NEW.ID_ESTADO IS NULL)
BEGIN
    :NEW.ID_ESTADO := seq_est_tarjetas.NEXTVAL;
END;
/

-- Trigger para historial_auditoria
CREATE OR REPLACE TRIGGER trg_historial_auditoria_id
BEFORE INSERT ON HISTAUDTORIAS
FOR EACH ROW
WHEN (NEW.ID_AUDITORIA IS NULL)
BEGIN
    :NEW.ID_AUDITORIA := seq_historial_auditoria.NEXTVAL;
END;
/

-- Trigger para historial_prestamos
CREATE OR REPLACE TRIGGER trg_historial_prestamos_id
BEFORE INSERT ON HISTPRES
FOR EACH ROW
WHEN (NEW.ID_HISTORIAL_PRESTAMO IS NULL)
BEGIN
    :NEW.ID_HISTORIAL_PRESTAMO := seq_historial_prestamos.NEXTVAL;
END;
/

-- Trigger para historial_saldos
CREATE OR REPLACE TRIGGER trg_historial_saldos_id
BEFORE INSERT ON HISTORIAL_SALDOS
FOR EACH ROW
WHEN (NEW.ID_HISTORIAL IS NULL)
BEGIN
    :NEW.ID_HISTORIAL := seq_historial_saldos.NEXTVAL;
END;
/

-- Trigger para municipios
CREATE OR REPLACE TRIGGER trg_municipios_id
BEFORE INSERT ON MUNICIPIOS
FOR EACH ROW
WHEN (NEW.ID_MUNICIPIO IS NULL)
BEGIN
    :NEW.ID_MUNICIPIO := seq_municipios.NEXTVAL;
END;
/

-- Trigger para prestamos
CREATE OR REPLACE TRIGGER trg_prestamos_id
BEFORE INSERT ON PRESTAMOS
FOR EACH ROW
WHEN (NEW.ID_PRESTAMO IS NULL)
BEGIN
    :NEW.ID_PRESTAMO := seq_prestamos.NEXTVAL;
END;
/

-- Trigger para roles
CREATE OR REPLACE TRIGGER trg_roles_id
BEFORE INSERT ON ROLES
FOR EACH ROW
WHEN (NEW.ID_ROL IS NULL)
BEGIN
    :NEW.ID_ROL := seq_roles.NEXTVAL;
END;
/

-- Trigger para seguridad_acceso
CREATE OR REPLACE TRIGGER trg_seguridad_acceso_id
BEFORE INSERT ON SECACCES
FOR EACH ROW
WHEN (NEW.ID_ACCESO IS NULL)
BEGIN
    :NEW.ID_ACCESO := seq_seguridad_acceso.NEXTVAL;
END;
/

-- Trigger para sucs_agens
CREATE OR REPLACE TRIGGER trg_sucs_agens_id
BEFORE INSERT ON SUCS_AGENS
FOR EACH ROW
WHEN (NEW.ID_SUC_AGEN IS NULL)
BEGIN
    :NEW.ID_SUC_AGEN := seq_sucs_agens.NEXTVAL;
END;
/

-- Trigger para tarjs_cred
CREATE OR REPLACE TRIGGER trg_tarjs_cred_id
BEFORE INSERT ON TARJS_CRED
FOR EACH ROW
WHEN (NEW.ID_TARJETA IS NULL)
BEGIN
    :NEW.ID_TARJETA := seq_tarjs_cred.NEXTVAL;
END;
/

-- Trigger para tipocuentas
CREATE OR REPLACE TRIGGER trg_tipocuentas_id
BEFORE INSERT ON TIPOCUENTAS
FOR EACH ROW
WHEN (NEW.ID_TIPO_CUENTA IS NULL)
BEGIN
    :NEW.ID_TIPO_CUENTA := seq_tipocuentas.NEXTVAL;
END;
/

-- Trigger para tipo_sucs_agens
CREATE OR REPLACE TRIGGER trg_tipo_sucs_agens_id
BEFORE INSERT ON TIPSUCAGENS
FOR EACH ROW
WHEN (NEW.ID_TIPO_SUC_AGEN IS NULL)
BEGIN
    :NEW.ID_TIPO_SUC_AGEN := seq_tipo_sucs_agens.NEXTVAL;
END;
/

-- Trigger para tipo_transacs
CREATE OR REPLACE TRIGGER trg_tipo_transacs_id
BEFORE INSERT ON TIPO_TRANSACS
FOR EACH ROW
WHEN (NEW.ID_TIPO_TRAN IS NULL)
BEGIN
    :NEW.ID_TIPO_TRAN := seq_tipo_transacs.NEXTVAL;
END;
/

-- Trigger para transacciones
CREATE OR REPLACE TRIGGER trg_transacciones_id
BEFORE INSERT ON TRANSACCIONES
FOR EACH ROW
WHEN (NEW.ID_TRANSACCION IS NULL)
BEGIN
    :NEW.ID_TRANSACCION := seq_transacciones.NEXTVAL;
END;
/

-- Trigger para transacciones_interbancarias
CREATE OR REPLACE TRIGGER trg_transacciones_interbancarias_id
BEFORE INSERT ON TRANINTERBS
FOR EACH ROW
WHEN (NEW.ID_INTERBANCARIA IS NULL)
BEGIN
    :NEW.ID_INTERBANCARIA := seq_transacciones_interbancarias.NEXTVAL;
END;
/

-- Trigger para bovedas
CREATE OR REPLACE TRIGGER trg_bovedas_id
BEFORE INSERT ON BOVEDAS
FOR EACH ROW
WHEN (NEW.ID_BOVEDA IS NULL)
BEGIN
    :NEW.ID_BOVEDA := seq_bovedas.NEXTVAL;
END;
/


-- Trigger para historial_auditoria
CREATE OR REPLACE TRIGGER trg_historial_auditoria_id
BEFORE INSERT ON HISTAUDTORIAS
FOR EACH ROW
WHEN (NEW.ID_AUDITORIA IS NULL)
BEGIN
    :NEW.ID_AUDITORIA := seq_historial_auditoria.NEXTVAL;
END;
/